// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4txqzqjVMhqjSZOppGyo-NQ2qhU6vnHM',
    appId: '1:894766207106:web:1dd51cf33bc8227b5e249b',
    messagingSenderId: '894766207106',
    projectId: 'rool-tooapps',
    authDomain: 'rool-tooapps.firebaseapp.com',
    storageBucket: 'rool-tooapps.appspot.com',
    measurementId: 'G-G6LJ9XD1E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBazPLd2bEJHDXZookVKlns8gyGiIRWG7w',
    appId: '1:894766207106:android:8f1bbeafabd41eaf5e249b',
    messagingSenderId: '894766207106',
    projectId: 'rool-tooapps',
    storageBucket: 'rool-tooapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzyX4X_3xog8ZTL5Jf7R56TvFtvgh6ES4',
    appId: '1:894766207106:ios:61b4abba33d7bab45e249b',
    messagingSenderId: '894766207106',
    projectId: 'rool-tooapps',
    storageBucket: 'rool-tooapps.appspot.com',
    iosBundleId: 'apps.too.rool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzyX4X_3xog8ZTL5Jf7R56TvFtvgh6ES4',
    appId: '1:894766207106:ios:61b4abba33d7bab45e249b',
    messagingSenderId: '894766207106',
    projectId: 'rool-tooapps',
    storageBucket: 'rool-tooapps.appspot.com',
    iosBundleId: 'apps.too.rool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4txqzqjVMhqjSZOppGyo-NQ2qhU6vnHM',
    appId: '1:894766207106:web:ba84b0fd6c2fed1a5e249b',
    messagingSenderId: '894766207106',
    projectId: 'rool-tooapps',
    authDomain: 'rool-tooapps.firebaseapp.com',
    storageBucket: 'rool-tooapps.appspot.com',
    measurementId: 'G-DNYNW1GBLM',
  );
}
